apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: quiz-app
  template:
    metadata:
      labels:
        app: quiz-app
    spec:
      containers:
      - name: quiz-app
        image: hasikagade123/quiz:hasika1
        ports:

        - containerPort: 5000








