apiVersion: v1
kind: Service
metadata:
  name: quiz-app-service
spec:
  type: NodePort
  selector:
    app: quiz-app
  ports:
  - port: 5000
    targetPort: 5000

    nodePort: 30022



